import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'ml-codex',
    },
  ],
};

export default sidebars;
